# Generated by Django 3.2.12 on 2022-04-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_rename_mentors_mentor'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='High_school',
            new_name='HighSchool',
        ),
    ]
