# Generated by Django 3.2.12 on 2022-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentors',
            name='uni',
        ),
        migrations.AddField(
            model_name='mentors',
            name='uni',
            field=models.ManyToManyField(blank=True, null=True, to='school.Uni'),
        ),
    ]
