# Generated by Django 3.2.12 on 2022-04-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('mentor', '0003_auto_20220326_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentors',
            new_name='Mentor',
        ),
    ]
