# Generated by Django 3.2.12 on 2022-07-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_high_school_highschool'),
        ('mentor', '0004_rename_mentors_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='high_school',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='uni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.uni'),
        ),
    ]
